application: save-a-pet
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: jinja2
  version: 2.6
  

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.py
